### ISSUE TITLE
Error Generating PDF From PHP

### ISSUE THREAD

**Issue by jfreak53** [KnpLabs/snappy#189]
From PHP5 I get this error:

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The file '/tmp/knp_snappy561d756266f962.60990762.pdf' was not created (command: /usr/bin/wkhtmltopdf --lowquality --encoding 'UTF-8' '/tmp/knp_snappy561d756266ecb2.54827198.html' '/tmp/knp_snappy561d756266f962.60990762.pdf').' in /var/www/quantum/Knp/Snappy/AbstractGenerator.php:276\nStack trace:\n#0 /var/www/quantum/Knp/Snappy/AbstractGenerator.php(132): Knp\\Snappy\\AbstractGenerator->checkOutput('/tmp/knp_snappy...', '/usr/bin/wkhtml...')\n#1 /var/www/quantum/Knp/Snappy/Pdf.php(58): Knp\\Snappy\\AbstractGenerator->generate('/tmp/knp_snappy...', '/tmp/knp_snappy...', Array, false)\n#2 /var/www/quantum/Knp/Snappy/AbstractGenerator.php(154): Knp\\Snappy\\Pdf->generate('/tmp/knp_snappy...', '/tmp/knp_snappy...', Array)\n#3 /var/www/quantum/Knp/Snappy/AbstractGenerator.php(170): Knp\\Snappy\\AbstractGenerator->getOutput('/tmp/knp_snappy...', Array)\n#4 /var/www/quantum/index.php(123): Knp\\Snappy\\AbstractGenerator->getOutputFromHtml('<meta charset="...')\n#5 {main}\n  thrown in /var/www/quantum/Knp/Snappy/AbstractGenerator.php on line 276
```

But if I run that command `/usr/bin/wkhtmltopdf --lowquality --encoding 'UTF-8' '/tmp/knp_snappy561d756266ecb2.54827198.html' '/tmp/knp_snappy561d756266f962.60990762.pdf'` from the CLI it creates the PDF just fine. This is from Linux with Apache2 and PHP5.

**Comment by akovalyov** [comment]
@jfreak53 have you solved the issue? Does your binary have the appropriate permissions to be executed?

**Comment by jfreak53** [comment]
Yeah, I was missing a few ghost font libraries it seems. Forget what they were though, I'll find out and post 'em back here for other's.

**Comment by h00dstoker** [comment]
Hello my friend, 

send the libraries.

**Comment by jfreak53** [comment]
CentOS I install these:

```
yum install libXext libXrender xorg-x11-fonts-Type1 xorg-x11-fonts-75dpi urw-fonts
```

**Comment by h00dstoker** [comment]
Tks man.
:+1:

**Comment by DDiimmkkaass** [comment]
Thanks!
